[tool.black]
line-length = 119
skip-string-normalization = 1
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.coverage.run]
branch = true
command_line = 'manage.py test'
source = ['./']
omit = ['config/*'] #TODO 'manage.py'

[tool.coverage.report]
precision = 2
skip_covered = true
show_missing = true
fail_under = 75